<?php

namespace Book\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Books
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{
}
